{% set name = "zuko" %}
{% set version = "1.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/zuko-{{ version }}.tar.gz
  sha256: 00f246802d3f486183185529ba22e0b2bf691397e03b28150a5cf713fa0da758

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - numpy >=1.20.0
    - pytorch >=1.12.0

test:
  imports:
    - zuko
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Normalizing flows in PyTorch
  home: https://github.com/probabilists/zuko
  dev_url: https://github.com/probabilists/zuko
  doc_url: https://zuko.readthedocs.io/en/stable/
  doc_source_url: https://github.com/probabilists/zuko/tree/master/docs
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - wtclarke
    - frankier
