{% set name = "zuko" %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/zuko-{{ version }}.tar.gz
  sha256: 4ce10928caaad0b567e6e070737188e8c4974c5a74221847c601b069020bec62

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy >=1.20.0
    - pytorch >=1.12.0

test:
  imports:
    - zuko
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Normalizing flows in PyTorch
  home: https://github.com/probabilists/zuko
  dev_url: https://github.com/probabilists/zuko
  doc_url: https://zuko.readthedocs.io/en/stable/
  doc_source_url: https://github.com/probabilists/zuko/tree/master/docs
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - wtclarke
    - frankier
